spring:
  datasource:
    url: jdbc:h2:mem:notice-test;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  cache:
    type: simple

file:
  upload-dir: ./build/test-uploads