spring:
  datasource:
    url: jdbc:h2:mem:notice;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false         # 서비스 계층에서 필요한 연관만 로딩
  properties:
    hibernate.format_sql: true
    hibernate.jdbc.batch_size: 50
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      host: localhost
      port: 6379
file:
  upload-dir: ./uploads
logging:
  level:
    org.hibernate.SQL: warn